In [1]:
from gssutils import *

if is_interactive():
    import requests
    from cachecontrol import CacheControl
    from cachecontrol.caches.file_cache import FileCache
    from cachecontrol.heuristics import LastModified
    from pathlib import Path

    session = CacheControl(requests.Session(),
                           cache=FileCache('.cache'),
                           heuristic=LastModified())

    sourceFolder = Path('in')
    sourceFolder.mkdir(exist_ok=True)

    inputURL = ('https://fingertipsws.phe.org.uk/api/all_data/csv/by_profile_id?parent_area_code=e92000001&parent_area_type_id=6&child_area_type_id=101&profile_id=87')
    inputFile = sourceFolder / 'LocalAlcoholProfilesforEngland-CountyUA.data.csv'
    response = session.get(inputURL, verify=False)
    with open(inputFile, 'wb') as f:
      f.write(response.content)

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

https://fingertipsws.phe.org.uk/api/all_data/csv/by_profile_id?parent_area_code=e92000001&parent_area_type_id=6&child_area_type_id=101&profile_id=87

In [2]:
oldFile = pd.read_csv(inputFile)
oldFile

,Indicator ID,Indicator Name,Parent Code,Parent Name,Area Code,Area Name,Area Type,Sex,Age,Category Type,...,Upper CI 99.8 limit,Count,Denominator,Value note,Recent Trend,Compared to England value or percentiles,Compared to Region value or percentiles,Time period Sortable,New data,Compared to goal
0,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,NaN,...,NaN,185985.160125,2.543493e+07,NaN,NaN,Not compared,Not compared,20080000,NaN,NaN
1,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,20083.051469,2.338527e+06,Value for Hackney and City of London combined,NaN,Worse,Not compared,20080000,NaN,NaN
2,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,14510.012802,1.705740e+06,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
3,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,14100.592626,1.768016e+06,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
4,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,19561.638203,2.455500e+06,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
5,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,13388.960624,1.813235e+06,Value for Cornwall & Isles of Scilly combined,NaN,Similar,Not compared,20080000,NaN,NaN
6,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,21994.552990,2.743376e+06,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
7,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,23221.531396,3.411509e+06,NaN,NaN,Better,Not compared,20080000,NaN,NaN
8,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,21218.300337,3.145237e+06,NaN,NaN,Better,Not compared,20080000,NaN,NaN
9,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,19624.380483,2.990348e+06,Value for Hackney and City of London combined,NaN,Better,Not compared,20080000,NaN,NaN
10,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,15870.521779,3.063438e+06,Value for Cornwall & Isles of Scilly combined,NaN,Better,Not compared,20080000,NaN,NaN
11,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,33043.791633,3.865642e+06,Value for Hackney and City of London combined,NaN,Worse,Not compared,20080000,NaN,NaN
12,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,30111.413570,3.738924e+06,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
13,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,26542.781074,3.419448e+06,Value for Cornwall & Isles of Scilly combined,NaN,Worse,Not compared,20080000,NaN,NaN
14,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,17972.900720,2.266453e+06,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
15,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,16231.361658,2.273988e+06,NaN,NaN,Better,Not compared,20080000,NaN,NaN
16,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,15392.760371,2.339545e+06,NaN,NaN,Better,Not compared,20080000,NaN,NaN
17,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,13131.699272,2.056519e+06,NaN,NaN,Better,Not compared,20080000,NaN,NaN
18,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,11217.623096,1.823353e+06,Value for Hackney and City of London combined,NaN,Better,Not compared,20080000,NaN,NaN
19,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,11327.534900,1.986405e+06,Value for Cornwall & Isles of Scilly combined,NaN,Better,Not compared,20080000,NaN,NaN
20,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,8601.676415,1.664649e+06,NaN,NaN,Better,Not compared,20080000,NaN,NaN
21,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Female,All ages,NaN,...,NaN,113022.942218,2.638093e+07,NaN,NaN,Not compared,Not compared,20080000,NaN,NaN
22,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,10771.455553,2.395085e+06,Value for Hackney and City of London combined,NaN,Worse,Not compared,20080000,NaN,NaN
23,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,8516.319044,1.757441e+06,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
24,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,8401.824251,1.814843e+06,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
25,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,11804.507075,2.548598e+06,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
26,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,8190.917309,1.887745e+06,Value for Cornwall & Isles of Scilly combined,NaN,Similar,Not compared,20080000,NaN,NaN
27,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,13185.645528,2.851726e+06,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
28,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,14757.659779,3.548267e+06,NaN,NaN,Better,Not compared,20080000,NaN,NaN
29,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,Country,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,14390.769699,3.295367e+06,NaN,NaN,Similar,Not compared,20080000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180785,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000004,Bexley,District & UA,Not applicable,Not applicable,NaN,...,NaN,527.000000,6.057630e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180786,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000005,Brent,District & UA,Not applicable,Not applicable,NaN,...,NaN,800.000000,4.323250e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180787,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000006,Bromley,District & UA,Not applicable,Not applicable,NaN,...,NaN,621.000000,1.501347e+02,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180788,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000007,Camden,District & UA,Not applicable,Not applicable,NaN,...,NaN,1699.000000,2.178950e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180789,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000008,Croydon,District & UA,Not applicable,Not applicable,NaN,...,NaN,0.000000,NaN,Value missing in source data,Cannot be calculated,Better,Similar,20160000,NaN,NaN
180790,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000009,Ealing,District & UA,Not applicable,Not applicable,NaN,...,NaN,872.000000,5.554470e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180791,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000010,Enfield,District & UA,Not applicable,Not applicable,NaN,...,NaN,756.000000,8.083100e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180792,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000011,Greenwich,District & UA,Not applicable,Not applicable,NaN,...,NaN,756.000000,4.733400e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180793,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000012,Hackney,District & UA,Not applicable,Not applicable,NaN,...,NaN,1318.000000,1.904920e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180794,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000013,Hammersmith and Fulham,District & UA,Not applicable,Not applicable,NaN,...,NaN,818.000000,1.639760e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180795,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000014,Haringey,District & UA,Not applicable,Not applicable,NaN,...,NaN,660.000000,2.959830e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180796,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000015,Harrow,District & UA,Not applicable,Not applicable,NaN,...,NaN,525.000000,5.046340e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180797,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000016,Havering,District & UA,Not applicable,Not applicable,NaN,...,NaN,541.000000,1.123497e+02,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180798,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000017,Hillingdon,District & UA,Not applicable,Not applicable,NaN,...,NaN,778.000000,1.157002e+02,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180799,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000018,Hounslow,District & UA,Not applicable,Not applicable,NaN,...,NaN,744.000000,5.597790e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180800,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000019,Islington,District & UA,Not applicable,Not applicable,NaN,...,NaN,1169.000000,1.485650e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180801,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000020,Kensington and Chelsea,District & UA,Not applicable,Not applicable,NaN,...,NaN,988.000000,1.212380e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180802,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000021,Kingston upon Thames,District & UA,Not applicable,Not applicable,NaN,...,NaN,561.000000,3.726120e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180803,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000022,Lambeth,District & UA,Not applicable,Not applicable,NaN,...,NaN,1290.000000,2.681010e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180804,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000023,Lewisham,District & UA,Not applicable,Not applicable,NaN,...,NaN,675.000000,3.514880e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180805,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000024,Merton,District & UA,Not applicable,Not applicable,NaN,...,NaN,503.000000,3.762480e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180806,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000025,Newham,District & UA,Not applicable,Not applicable,NaN,...,NaN,671.000000,3.620170e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180807,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000026,Redbridge,District & UA,Not applicable,Not applicable,NaN,...,NaN,576.000000,5.641920e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180808,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000027,Richmond upon Thames,District & UA,Not applicable,Not applicable,NaN,...,NaN,709.000000,5.740700e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180809,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000028,Southwark,District & UA,Not applicable,Not applicable,NaN,...,NaN,1269.000000,2.886210e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180810,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000029,Sutton,District & UA,Not applicable,Not applicable,NaN,...,NaN,381.000000,4.384710e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180811,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000030,Tower Hamlets,District & UA,Not applicable,Not applicable,NaN,...,NaN,1010.000000,1.978640e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180812,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000031,Waltham Forest,District & UA,Not applicable,Not applicable,NaN,...,NaN,702.000000,3.880780e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180813,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000032,Wandsworth,District & UA,Not applicable,Not applicable,NaN,...,NaN,1030.000000,3.426340e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN
180814,92772,18.01 - Number of premises licensed to sell al...,E12000007,London region,E09000033,Westminster,District & UA,Not applicable,Not applicable,NaN,...,NaN,3389.000000,2.148700e+01,NaN,Cannot be calculated,Worse,Worse,20160000,NaN,NaN

In [3]:
list(oldFile)

['Indicator ID',
 'Indicator Name',
 'Parent Code',
 'Parent Name',
 'Area Code',
 'Area Name',
 'Area Type',
 'Sex',
 'Age',
 'Category Type',
 'Category',
 'Time period',
 'Value',
 'Lower CI 95.0 limit',
 'Upper CI 95.0 limit',
 'Lower CI 99.8 limit',
 'Upper CI 99.8 limit',
 'Count',
 'Denominator',
 'Value note',
 'Recent Trend',
 'Compared to England value or percentiles',
 'Compared to Region value or percentiles',
 'Time period Sortable',
 'New data',
 'Compared to goal']

In [4]:
oldFile['Area Type'].unique()

array(['Country', 'Region', 'District & UA'], dtype=object)

In [5]:
oldFile.columns = ['Geography' if x=='Area Code' else x for x in oldFile.columns]

In [6]:
oldFile.columns = ['Period' if x=='Time period' else x for x in oldFile.columns]

In [7]:
new_table = oldFile[['Geography','Period','Sex', 'Age','Indicator ID','Indicator Name','Category Type',
                     'Category','Value','Lower CI 95.0 limit','Upper CI 95.0 limit','Value note']]

In [8]:
if is_interactive():
    destinationFolder = Path('out')
    destinationFolder.mkdir(exist_ok=True, parents=True)
    new_table.to_csv(destinationFolder / ('alcoholprofilesdistrict.csv'), index = False)