In [1]:
from gssutils import *
import requests

scraper = Scraper('https://www.gov.uk/government/collections/local-alcohol-profiles-for-england-lape')
scraper

## Local Alcohol Profiles for England (LAPE)

This is a catalog of datasets; choose one from the following:

* Local Alcohol Profiles for England: February 2019 data update
* Local Alcohol Profiles for England: December 2018 data update
* Local Alcohol Profiles for England: September 2018 update
* Local Alcohol Profiles for England: July 2018 update
* Local Alcohol Profiles for England: February 2018 update
* Local Alcohol Profiles for England: November 2017 update
* Local Alcohol Profiles for England: May 2017 data update
* Local Alcohol Profiles for England: March 2017 data update
* Local Alcohol Profiles for England (LAPE): February 2017 data update
* Local Alcohol Profiles for England: hospital admissions indicators, 2016 annual data update
* Local Alcohol Profiles for England: mortality indicators, 2016 annual data update
* Local Alcohol Profiles for England: 2015 annual data update
* Local Alcohol Profiles for England: April 2014 annual data update

In [2]:
scraper.select_dataset(latest=True)
scraper

## Local Alcohol Profiles for England: February 2019 data update

Update of Indicators in the Local Alcohol Profiles for England (LAPE) interactive tool.

### Description

Public Health England (PHE) has published an update to [Local Alcohol Profiles
for England (LAPE)](http://fingertips.phe.org.uk/profile/local-alcohol-
profiles).

The LAPE interactive tool presents a range of alcohol-related indicators and
allows users to view and analyse data in a user-friendly format.

The aim of the profile is to provide information for local government, health
organisations, commissioners and other agencies to monitor the impact of
alcohol on local communities, and to monitor the services and initiatives that
have been put in place to prevent and reduce the harmful impact of alcohol.

This release includes an update of 13 alcohol-specific and alcohol-related
hospital admissions indicators and further data breakdowns by age group and
condition.

[View previous Local Alcohol Profiles for England
updates](https://www.gov.uk/government/collections/local-alcohol-profiles-for-
england-lape)

Relevant information from LAPE to aid in the understanding of alcohol-related
harm in a local population is available from the [UK Government Web
Archive](http://webarchive.nationalarchives.gov.uk/20171107173418/http://www.lape.org.uk/).

  *[PHE]: Public Health England
  *[LAPE]: Local alcohol profiles for England



### Distributions

1. Local Alcohol Profiles for England ([None](http://fingertips.phe.org.uk/profile/local-alcohol-profiles))
1. Local Alcohol Profiles for England: short statistical commentary, February 2019 ([None](https://www.gov.uk/government/publications/local-alcohol-profiles-for-england-february-2019-data-update/local-alcohol-profiles-for-england-short-statistical-commentary-february-2019))
1. Local Alcohol Profiles for England: short commentary slideset, February 2019 ([None](https://www.slideshare.net/PublicHealthEngland/local-alcohol-profiles-for-england-february-2019))
1. Pre-release access list: LAPE update, February 2019 ([None](https://www.gov.uk/government/publications/local-alcohol-profiles-for-england-february-2019-data-update/pre-release-access-list-lape-update-february-2019))

In [3]:
dist = scraper.distribution(title='Local Alcohol Profiles for England')
dist

In [4]:
dist.downloadURL = 'https://fingertipsws.phe.org.uk/api/all_data/csv/' + \
    'by_profile_id?parent_area_code=e92000001&parent_area_type_id=6&child_area_type_id=102&profile_id=87'
dist.mediaType = 'text/csv'

from io import BytesIO
table = pd.read_csv(BytesIO(scraper.session.get(dist.downloadURL, verify=False).content))
table

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

,Indicator ID,Indicator Name,Parent Code,Parent Name,Area Code,Area Name,Area Type,Sex,Age,Category Type,...,Upper CI 99.8 limit,Count,Denominator,Value note,Recent Trend,Compared to England value or percentiles,Compared to Region value or percentiles,Time period Sortable,New data,Compared to goal
0,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,NaN,...,NaN,185985.160125,25434926.0,NaN,NaN,Not compared,Not compared,20080000,NaN,NaN
1,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,20083.051469,2338527.0,Value for Hackney and City of London combined,NaN,Worse,Not compared,20080000,NaN,NaN
2,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,14510.012802,1705740.0,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
3,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,14100.592626,1768016.0,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
4,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,19561.638203,2455500.0,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
5,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,13388.960624,1813235.0,Value for Cornwall & Isles of Scilly combined,NaN,Similar,Not compared,20080000,NaN,NaN
6,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,21994.552990,2743376.0,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
7,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,23221.531396,3411509.0,NaN,NaN,Better,Not compared,20080000,NaN,NaN
8,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,21218.300337,3145237.0,NaN,NaN,Better,Not compared,20080000,NaN,NaN
9,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,19624.380483,2990348.0,Value for Hackney and City of London combined,NaN,Better,Not compared,20080000,NaN,NaN
10,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,County & UA deprivation deciles in England (IM...,...,NaN,15870.521779,3063438.0,Value for Cornwall & Isles of Scilly combined,NaN,Better,Not compared,20080000,NaN,NaN
11,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,33043.791633,3865642.0,Value for Hackney and City of London combined,NaN,Worse,Not compared,20080000,NaN,NaN
12,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,30111.413570,3738924.0,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
13,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,26542.781074,3419448.0,Value for Cornwall & Isles of Scilly combined,NaN,Worse,Not compared,20080000,NaN,NaN
14,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,17972.900720,2266453.0,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
15,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,16231.361658,2273988.0,NaN,NaN,Better,Not compared,20080000,NaN,NaN
16,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,15392.760371,2339545.0,NaN,NaN,Better,Not compared,20080000,NaN,NaN
17,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,13131.699272,2056519.0,NaN,NaN,Better,Not compared,20080000,NaN,NaN
18,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,11217.623096,1823353.0,Value for Hackney and City of London combined,NaN,Better,Not compared,20080000,NaN,NaN
19,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,11327.534900,1986405.0,Value for Cornwall & Isles of Scilly combined,NaN,Better,Not compared,20080000,NaN,NaN
20,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Male,All ages,District & UA deprivation deciles in England (...,...,NaN,8601.676415,1664649.0,NaN,NaN,Better,Not compared,20080000,NaN,NaN
21,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Female,All ages,NaN,...,NaN,113022.942218,26380927.0,NaN,NaN,Not compared,Not compared,20080000,NaN,NaN
22,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,10771.455553,2395085.0,Value for Hackney and City of London combined,NaN,Worse,Not compared,20080000,NaN,NaN
23,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,8516.319044,1757441.0,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
24,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,8401.824251,1814843.0,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
25,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,11804.507075,2548598.0,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
26,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,8190.917309,1887745.0,Value for Cornwall & Isles of Scilly combined,NaN,Similar,Not compared,20080000,NaN,NaN
27,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,13185.645528,2851726.0,NaN,NaN,Worse,Not compared,20080000,NaN,NaN
28,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,14757.659779,3548267.0,NaN,NaN,Better,Not compared,20080000,NaN,NaN
29,91414,10.01 - Admission episodes for alcohol-related...,NaN,NaN,E92000001,England,England,Female,All ages,County & UA deprivation deciles in England (IM...,...,NaN,14390.769699,3295367.0,NaN,NaN,Similar,Not compared,20080000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104150,93193,20.01 - Percentage of dependent drinkers,E12000007,London region,E09000031,Waltham Forest,County & UA,Persons,18+ yrs,NaN,...,NaN,2948.230000,203724.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104151,93193,20.01 - Percentage of dependent drinkers,E12000007,London region,E09000032,Wandsworth,County & UA,Persons,18+ yrs,NaN,...,NaN,3742.940000,252442.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104152,93193,20.01 - Percentage of dependent drinkers,E12000007,London region,E09000033,Westminster,County & UA,Persons,18+ yrs,NaN,...,NaN,2728.050000,192598.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104153,93193,20.01 - Percentage of dependent drinkers,E12000008,South East region,E10000002,Buckinghamshire,County & UA,Persons,18+ yrs,NaN,...,NaN,3487.970000,403013.0,NaN,Cannot be calculated,Better,Similar,20140000,NaN,NaN
104154,93193,20.01 - Percentage of dependent drinkers,E12000006,East of England region,E10000003,Cambridgeshire,County & UA,Persons,18+ yrs,NaN,...,NaN,5577.720000,508328.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104155,93193,20.01 - Percentage of dependent drinkers,E12000002,North West region,E10000006,Cumbria,County & UA,Persons,18+ yrs,NaN,...,NaN,5833.620000,404581.0,NaN,Cannot be calculated,Similar,Better,20140000,NaN,NaN
104156,93193,20.01 - Percentage of dependent drinkers,E12000004,East Midlands region,E10000007,Derbyshire,County & UA,Persons,18+ yrs,NaN,...,NaN,8534.300000,625782.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104157,93193,20.01 - Percentage of dependent drinkers,E12000009,South West region,E10000008,Devon,County & UA,Persons,18+ yrs,NaN,...,NaN,7094.650000,623151.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104158,93193,20.01 - Percentage of dependent drinkers,E12000009,South West region,E10000009,Dorset,County & UA,Persons,18+ yrs,NaN,...,NaN,3491.950000,341035.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104159,93193,20.01 - Percentage of dependent drinkers,E12000008,South East region,E10000011,East Sussex,County & UA,Persons,18+ yrs,NaN,...,NaN,5296.830000,434374.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104160,93193,20.01 - Percentage of dependent drinkers,E12000006,East of England region,E10000012,Essex,County & UA,Persons,18+ yrs,NaN,...,NaN,12205.220000,1131693.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104161,93193,20.01 - Percentage of dependent drinkers,E12000009,South West region,E10000013,Gloucestershire,County & UA,Persons,18+ yrs,NaN,...,NaN,5193.560000,487526.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104162,93193,20.01 - Percentage of dependent drinkers,E12000008,South East region,E10000014,Hampshire,County & UA,Persons,18+ yrs,NaN,...,NaN,9980.440000,1064677.0,NaN,Cannot be calculated,Better,Similar,20140000,NaN,NaN
104163,93193,20.01 - Percentage of dependent drinkers,E12000006,East of England region,E10000015,Hertfordshire,County & UA,Persons,18+ yrs,NaN,...,NaN,8660.550000,893020.0,NaN,Cannot be calculated,Better,Similar,20140000,NaN,NaN
104164,93193,20.01 - Percentage of dependent drinkers,E12000008,South East region,E10000016,Kent,County & UA,Persons,18+ yrs,NaN,...,NaN,14052.040000,1182104.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104165,93193,20.01 - Percentage of dependent drinkers,E12000002,North West region,E10000017,Lancashire,County & UA,Persons,18+ yrs,NaN,...,NaN,14199.260000,939980.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104166,93193,20.01 - Percentage of dependent drinkers,E12000004,East Midlands region,E10000018,Leicestershire,County & UA,Persons,18+ yrs,NaN,...,NaN,5180.010000,533105.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104167,93193,20.01 - Percentage of dependent drinkers,E12000004,East Midlands region,E10000019,Lincolnshire,County & UA,Persons,18+ yrs,NaN,...,NaN,6807.250000,590137.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104168,93193,20.01 - Percentage of dependent drinkers,E12000006,East of England region,E10000020,Norfolk,County & UA,Persons,18+ yrs,NaN,...,NaN,9195.390000,710629.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104169,93193,20.01 - Percentage of dependent drinkers,E12000004,East Midlands region,E10000021,Northamptonshire,County & UA,Persons,18+ yrs,NaN,...,NaN,6535.390000,553700.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104170,93193,20.01 - Percentage of dependent drinkers,E12000003,Yorkshire and the Humber region,E10000023,North Yorkshire,County & UA,Persons,18+ yrs,NaN,...,NaN,5340.130000,484157.0,NaN,Cannot be calculated,Similar,Better,20140000,NaN,NaN
104171,93193,20.01 - Percentage of dependent drinkers,E12000004,East Midlands region,E10000024,Nottinghamshire,County & UA,Persons,18+ yrs,NaN,...,NaN,8345.980000,638312.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104172,93193,20.01 - Percentage of dependent drinkers,E12000008,South East region,E10000025,Oxfordshire,County & UA,Persons,18+ yrs,NaN,...,NaN,5373.150000,531363.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104173,93193,20.01 - Percentage of dependent drinkers,E12000009,South West region,E10000027,Somerset,County & UA,Persons,18+ yrs,NaN,...,NaN,5057.670000,432710.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104174,93193,20.01 - Percentage of dependent drinkers,E12000005,West Midlands region,E10000028,Staffordshire,County & UA,Persons,18+ yrs,NaN,...,NaN,8451.000000,690562.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104175,93193,20.01 - Percentage of dependent drinkers,E12000006,East of England region,E10000029,Suffolk,County & UA,Persons,18+ yrs,NaN,...,NaN,6570.940000,587180.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104176,93193,20.01 - Percentage of dependent drinkers,E12000008,South East region,E10000030,Surrey,County & UA,Persons,18+ yrs,NaN,...,NaN,7772.840000,906670.0,NaN,Cannot be calculated,Better,Similar,20140000,NaN,NaN
104177,93193,20.01 - Percentage of dependent drinkers,E12000005,West Midlands region,E10000031,Warwickshire,County & UA,Persons,18+ yrs,NaN,...,NaN,4937.160000,439332.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104178,93193,20.01 - Percentage of dependent drinkers,E12000008,South East region,E10000032,West Sussex,County & UA,Persons,18+ yrs,NaN,...,NaN,6966.730000,659564.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN
104179,93193,20.01 - Percentage of dependent drinkers,E12000005,West Midlands region,E10000034,Worcestershire,County & UA,Persons,18+ yrs,NaN,...,NaN,5407.140000,460490.0,NaN,Cannot be calculated,Similar,Similar,20140000,NaN,NaN

In [5]:
table.rename(index=str,
               columns={
                   'Indicator ID':'Indicator',
                   'Area Code' :'Geography',
                   'Time period':'Period',
                   'Upper CI 95.0 limit': 'CI Upper',
                   'Lower CI 95.0 limit': 'CI Lower'
               }, inplace = True)
table.count()

Indicator                                   104180
Indicator Name                              104180
Parent Code                                  92140
Parent Name                                  92140
Geography                                   104180
Area Name                                   104180
Area Type                                   104180
Sex                                         104180
Age                                         104180
Category Type                                11462
Category                                     11462
Period                                      104180
Value                                       101459
CI Lower                                    100816
CI Upper                                    100816
Lower CI 99.8 limit                          38553
Upper CI 99.8 limit                          38553
Count                                       101789
Denominator                                 101939
Value note                                    7391
Recent Trend                                 12122
Compared to England value or percentiles    104180
Compared to Region value or percentiles     104180
Time period Sortable                        104180
New data                                         0
Compared to goal                                 0
dtype: int64

In [6]:
table = table[table['Category Type'].isnull() == True]
table = table.dropna(subset=['Value'])
table.count()

Indicator                                   90514
Indicator Name                              90514
Parent Code                                 89942
Parent Name                                 89942
Geography                                   90514
Area Name                                   90514
Area Type                                   90514
Sex                                         90514
Age                                         90514
Category Type                                   0
Category                                        0
Period                                      90514
Value                                       90514
CI Lower                                    90013
CI Upper                                    90013
Lower CI 99.8 limit                         34399
Upper CI 99.8 limit                         34399
Count                                       90037
Denominator                                 89553
Value note                                   1059
Recent Trend                                10655
Compared to England value or percentiles    90514
Compared to Region value or percentiles     90514
Time period Sortable                        90514
New data                                        0
Compared to goal                                0
dtype: int64

In [7]:
table = table[['Geography','Period','Sex', 'Age','Indicator',\
                       'Value','CI Upper','CI Lower']]

In [8]:
table['Sex'] = table['Sex'].map(
    lambda x: {
        'Female' : 'F', 
        'Male' : 'M',
        'Persons': 'T' ,
        }.get(x, x))

In [9]:
table['Period'] = table['Period'].map(
    lambda x: {
        '2008/09' : 'gregorian-interval/2008-04-01T00:00:00/P1Y',
        '2009/10' : 'gregorian-interval/2009-04-01T00:00:00/P1Y', 
        '2010/11' : 'gregorian-interval/2010-04-01T00:00:00/P1Y', 
        '2011/12' : 'gregorian-interval/2011-04-01T00:00:00/P1Y', 
        '2012/13' : 'gregorian-interval/2012-04-01T00:00:00/P1Y', 
        '2013/14' : 'gregorian-interval/2013-04-01T00:00:00/P1Y',
        '2014/15' :'gregorian-interval/2014-04-01T00:00:00/P1Y', 
        '2015/16' : 'gregorian-interval/2015-04-01T00:00:00/P1Y', 
        '2016/17' : 'gregorian-interval/2016-04-01T00:00:00/P1Y', 
        '2017/18' :'gregorian-interval/2017-04-01T00:00:00/P1Y', 
        '2006/07 - 08/09': 'gregorian-interval/2006-04-01T00:00:00/P3Y',
       '2007/08 - 09/10' : 'gregorian-interval/2007-04-01T00:00:00/P3Y', 
        '2008/09 - 10/11': 'gregorian-interval/2008-04-01T00:00:00/P3Y', 
        '2009/10 - 11/12': 'gregorian-interval/2009-04-01T00:00:00/P3Y',
       '2010/11 - 12/13': 'gregorian-interval/2010-04-01T00:00:00/P3Y', 
        '2011/12 - 13/14': 'gregorian-interval/2011-04-01T00:00:00/P3Y', 
        '2012/13 - 14/15': 'gregorian-interval/2012-04-01T00:00:00/P3Y',
       '2013/14 - 15/16': 'gregorian-interval/2013-04-01T00:00:00/P3Y', 
        '2014/15 - 16/17': 'gregorian-interval/2014-04-01T00:00:00/P3Y', 
        '2015/16 - 17/18': 'gregorian-interval/2015-04-01T00:00:00/P3Y', 
        '2008' : 'year/2008',
       '2009': 'year/2009', '2010': 'year/2010', '2011': 'year/2011', '2012': 'year/2012', 
        '2013': 'year/2013', '2014': 'year/2014', '2015': 'year/2015', '2016': 'year/2016',
       '2017': 'year/2017', 
        '2006 - 08' :'gregorian-interval/2006-01-01T00:00:00/P2Y', 
        '2007 - 09' :'gregorian-interval/2007-01-01T00:00:00/P2Y', 
        '2008 - 10': 'gregorian-interval/2008-01-01T00:00:00/P2Y', 
        '2009 - 11' :'gregorian-interval/2009-01-01T00:00:00/P2Y',
       '2010 - 12': 'gregorian-interval/2010-01-01T00:00:00/P2Y', 
        '2011 - 13': 'gregorian-interval/2011-01-01T00:00:00/P2Y', 
        '2012 - 14' :'gregorian-interval/2012-01-01T00:00:00/P2Y', 
        '2013 - 15' : 'gregorian-interval/2013-01-01T00:00:00/P2Y', 
        '2014 - 16' :'gregorian-interval/2014-01-01T00:00:00/P2Y',
       '2015 - 17':'gregorian-interval/2015-01-01T00:00:00/P2Y', 
        '2004 - 06' :'gregorian-interval/2004-01-01T00:00:00/P2Y', 
        '2005 - 07': 'gregorian-interval/2005-01-01T00:00:00/P2Y', 
        '2011 - 14' : 'gregorian-interval/2011-01-01T00:00:00/P3Y'       
        }.get(x, x))

In [10]:
table['Age'].unique()

array(['All ages', '<18 yrs', '<75 yrs', '<40 yrs', '40-64 yrs',
       '65+ yrs', '16+ yrs', '16-64 yrs (M), 16-61 yrs (F)', '17+ yrs',
       '18+ yrs'], dtype=object)

In [11]:
table['Age'] = table['Age'].map(
    lambda x: {
        'All ages' : 'all', 
        '<18 yrs' : 'under-18', 
        '<75 yrs' : 'under-75', 
        '<40 yrs' : 'under-40', 
        '40-64 yrs' : '40-64',
        '65+ yrs' : 'ag1/65-plus', 
        '16+ yrs' : '16-plus', 
        '16-64 yrs (M), 16-61 yrs (F)' : 'agr/16-61-or-64',
        '17+ yrs' : '17-plus',
        '18+ yrs' : '18-plus', 
        '18-75 yrs' : "18-75 yrs"        
        }.get(x, x))

In [12]:
def user_perc(x):
    
    if str(x) == '91917':
        return 'Rate per 1,000 accidents'
    elif ((str(x) ==  '91182') | (str(x) == '92772')) :
        return 'Count'
    elif ((str(x) ==  '92447') | (str(x) == '91123') | (str(x) == '92774') |\
         (str(x) ==  '92776') | (str(x) == '92778') | (str(x) == '93193')) :
        return 'Percentage'
    elif ((str(x) ==  '92763') | (str(x) == '92765') | (str(x) == '92768') | (str(x) ==  '92770')) :
        return 'Volume'   
    else:
        return 'Rate per 100,000 persons'    
table['Measure Type'] = table.apply(lambda row: user_perc(row['Indicator']), axis = 1)

In [13]:
def user_perc(x):
    
    if str(x) == '92772':
        return 'premises-licensed-per-sq-km'
    elif ((str(x) ==  '92763') | (str(x) == '92765') | (str(x) == '92768') | (str(x) ==  '92770')) :
        return 'litres-alcohol-per-adult'   
    else:
        return 'people'    
table['Unit'] = table.apply(lambda row: user_perc(row['Indicator']), axis = 1)

In [14]:
table = table[['Geography','Period','Sex', 'Age','Indicator',\
                       'Value','Measure Type','Unit', 'CI Lower','CI Upper']]

In [15]:
out = Path('out')
out.mkdir(exist_ok=True, parents=True)
table.drop_duplicates().to_csv(out / 'observations.csv', index = False)

In [16]:
scraper.dataset.family = 'health'
scraper.dataset.theme = THEME['health-social-care']
with open(out / 'dataset.trig', 'wb') as metadata:
    metadata.write(scraper.generate_trig())

In [17]:
table

,Geography,Period,Sex,Age,Indicator,Value,Measure Type,Unit,CI Lower,CI Upper
0,E92000001,gregorian-interval/2008-04-01T00:00:00/P1Y,M,all,91414,793.263506,"Rate per 100,000 persons",people,789.571167,796.968513
21,E92000001,gregorian-interval/2008-04-01T00:00:00/P1Y,F,all,91414,440.472111,"Rate per 100,000 persons",people,437.890656,443.064933
42,E92000001,gregorian-interval/2008-04-01T00:00:00/P1Y,T,all,91414,605.754207,"Rate per 100,000 persons",people,603.565568,607.948765
63,E12000001,gregorian-interval/2008-04-01T00:00:00/P1Y,M,all,91414,1050.579307,"Rate per 100,000 persons",people,1031.891527,1069.514712
64,E12000002,gregorian-interval/2008-04-01T00:00:00/P1Y,M,all,91414,970.816892,"Rate per 100,000 persons",people,959.746226,981.980814
65,E12000003,gregorian-interval/2008-04-01T00:00:00/P1Y,M,all,91414,776.168682,"Rate per 100,000 persons",people,764.716922,787.745557
66,E12000004,gregorian-interval/2008-04-01T00:00:00/P1Y,M,all,91414,826.323598,"Rate per 100,000 persons",people,813.618393,839.173873
67,E12000005,gregorian-interval/2008-04-01T00:00:00/P1Y,M,all,91414,860.647074,"Rate per 100,000 persons",people,848.881539,872.532201
68,E12000006,gregorian-interval/2008-04-01T00:00:00/P1Y,M,all,91414,630.091761,"Rate per 100,000 persons",people,620.293219,640.004077
69,E12000007,gregorian-interval/2008-04-01T00:00:00/P1Y,M,all,91414,731.968931,"Rate per 100,000 persons",people,721.688781,742.350611
70,E12000008,gregorian-interval/2008-04-01T00:00:00/P1Y,M,all,91414,648.161785,"Rate per 100,000 persons",people,639.970788,656.429972
71,E12000009,gregorian-interval/2008-04-01T00:00:00/P1Y,M,all,91414,788.533108,"Rate per 100,000 persons",people,777.345445,799.840168
72,E12000001,gregorian-interval/2008-04-01T00:00:00/P1Y,F,all,91414,622.087856,"Rate per 100,000 persons",people,608.584909,635.813878
73,E12000002,gregorian-interval/2008-04-01T00:00:00/P1Y,F,all,91414,491.773349,"Rate per 100,000 persons",people,484.408653,499.221513
74,E12000003,gregorian-interval/2008-04-01T00:00:00/P1Y,F,all,91414,471.734604,"Rate per 100,000 persons",people,463.332825,480.249827
75,E12000004,gregorian-interval/2008-04-01T00:00:00/P1Y,F,all,91414,493.717741,"Rate per 100,000 persons",people,484.456879,503.110409
76,E12000005,gregorian-interval/2008-04-01T00:00:00/P1Y,F,all,91414,502.070771,"Rate per 100,000 persons",people,493.588133,510.662015
77,E12000006,gregorian-interval/2008-04-01T00:00:00/P1Y,F,all,91414,367.514076,"Rate per 100,000 persons",people,360.477199,374.653203
78,E12000007,gregorian-interval/2008-04-01T00:00:00/P1Y,F,all,91414,354.021327,"Rate per 100,000 persons",people,347.527614,360.602041
79,E12000008,gregorian-interval/2008-04-01T00:00:00/P1Y,F,all,91414,356.967341,"Rate per 100,000 persons",people,351.259386,362.744310
80,E12000009,gregorian-interval/2008-04-01T00:00:00/P1Y,F,all,91414,478.289671,"Rate per 100,000 persons",people,469.974548,486.714198
81,E12000001,gregorian-interval/2008-04-01T00:00:00/P1Y,T,all,91414,822.692918,"Rate per 100,000 persons",people,811.460006,834.041671
82,E12000002,gregorian-interval/2008-04-01T00:00:00/P1Y,T,all,91414,717.566921,"Rate per 100,000 persons",people,711.125200,724.052127
83,E12000003,gregorian-interval/2008-04-01T00:00:00/P1Y,T,all,91414,613.687489,"Rate per 100,000 persons",people,606.778261,620.655287
84,E12000004,gregorian-interval/2008-04-01T00:00:00/P1Y,T,all,91414,649.769234,"Rate per 100,000 persons",people,642.106135,657.500446
85,E12000005,gregorian-interval/2008-04-01T00:00:00/P1Y,T,all,91414,670.600523,"Rate per 100,000 persons",people,663.527972,677.729277
86,E12000006,gregorian-interval/2008-04-01T00:00:00/P1Y,T,all,91414,490.116550,"Rate per 100,000 persons",people,484.240826,496.045464
87,E12000007,gregorian-interval/2008-04-01T00:00:00/P1Y,T,all,91414,530.345749,"Rate per 100,000 persons",people,524.496300,536.241618
88,E12000008,gregorian-interval/2008-04-01T00:00:00/P1Y,T,all,91414,492.753353,"Rate per 100,000 persons",people,487.897736,497.645001
89,E12000009,gregorian-interval/2008-04-01T00:00:00/P1Y,T,all,91414,622.817730,"Rate per 100,000 persons",people,615.997472,629.694413
...,...,...,...,...,...,...,...,...,...,...
104150,E09000031,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.450000,Percentage,people,1.090000,2.040000
104151,E09000032,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.480000,Percentage,people,1.160000,2.020000
104152,E09000033,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.420000,Percentage,people,1.110000,1.900000
104153,E10000002,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,0.870000,Percentage,people,0.620000,1.260000
104154,E10000003,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.100000,Percentage,people,0.830000,1.510000
104155,E10000006,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.440000,Percentage,people,1.150000,1.860000
104156,E10000007,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.360000,Percentage,people,1.090000,1.780000
104157,E10000008,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.140000,Percentage,people,0.840000,1.620000
104158,E10000009,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.020000,Percentage,people,0.780000,1.400000
104159,E10000011,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.220000,Percentage,people,0.950000,1.630000
104160,E10000012,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.080000,Percentage,people,0.790000,1.520000
104161,E10000013,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.070000,Percentage,people,0.790000,1.490000
104162,E10000014,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,0.940000,Percentage,people,0.670000,1.340000
104163,E10000015,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,0.970000,Percentage,people,0.710000,1.380000
104164,E10000016,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.190000,Percentage,people,0.890000,1.640000
104165,E10000017,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.510000,Percentage,people,1.200000,1.980000
104166,E10000018,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,0.970000,Percentage,people,0.700000,1.390000
104167,E10000019,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.150000,Percentage,people,0.840000,1.630000
104168,E10000020,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.290000,Percentage,people,1.030000,1.700000
104169,E10000021,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.180000,Percentage,people,0.900000,1.600000
104170,E10000023,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.100000,Percentage,people,0.860000,1.480000
104171,E10000024,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.310000,Percentage,people,1.040000,1.720000
104172,E10000025,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.010000,Percentage,people,0.730000,1.450000
104173,E10000027,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.170000,Percentage,people,0.890000,1.610000
104174,E10000028,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.220000,Percentage,people,0.950000,1.640000
104175,E10000029,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.120000,Percentage,people,0.840000,1.550000
104176,E10000030,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,0.860000,Percentage,people,0.610000,1.250000
104177,E10000031,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.120000,Percentage,people,0.860000,1.530000
104178,E10000032,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.060000,Percentage,people,0.810000,1.440000
104179,E10000034,gregorian-interval/2014-04-01T00:00:00/P1Y,T,18-plus,93193,1.170000,Percentage,people,0.910000,1.570000